default:
  interruptible: true

stages:
  - build
  - test
  - sast

build:
  stage: build
  image: maven:3.8.8-eclipse-temurin
  artifacts:
    paths:
      - target/*.jar
  script:
    - mvn package -DskipTests=true

test:
  stage: test
  image: maven:3.8.8-eclipse-temurin
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml
  script:
    - mvn verify

sonarqube-check:
  stage: sast
  image: maven:3.6.3-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - mvn verify -e sonar:sonar -Dsonar.projectKey=joly.andrea_td-rest-api_AYyjSnLPu6L9HTu-0aYS
  allow_failure: true
  only:
    - main
