sonarqube-check:
  image: maven:3.6.3-jdk-11
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" 
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - mvn clean install -e
    - mvn verify sonar:sonar -Dsonar.projectKey=joly.andrea_td-rest-api_AYyjSnLPu6L9HTu-0aYS
  allow_failure: true
  only:
    - main
